# Generated by Django 2.1.1 on 2018-09-30 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20180929_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 30, 15, 38, 27, 583787), verbose_name='创建时间'),
        ),
    ]
