# Generated by Django 2.1.1 on 2018-10-10 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_auto_20181010_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 14, 21, 42, 931434), verbose_name='创建时间'),
        ),
    ]
